name: Docker Checks
run-name: Running Docker Image Checks by ${{ github.actor }}

env: 
  IMAGE_NAME: luqman-node-app

on:
  pull_request:
    branches:
      - main
    paths:
      - files/**

jobs:
  Docker-Check:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ job.status }}
    defaults:
      run:
        working-directory: files

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Docker build and tag
      run: |
        docker build -t ${{ env.IMAGE_NAME }}:latest .

    - name: Run image scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ env.IMAGE_NAME }}:latest'
        format: 'table'
        # exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'MEDIUM,HIGH,CRITICAL'
        output: 'docker-image-scan.json'

    - name: Upload Docker Trivy Report
      uses: actions/upload-artifact@v4.3.0
      with:
        name: docker-image-scan
        path: docker-image-scan.json
        
  Summary:
    needs: [Docker-Check]
    runs-on: ubuntu-latest
    steps:
      - name: Adding markdown
        run: |
          DOCKER_STATUS=${{ needs.Docker-Check.outputs.status }}

          echo '## 🚀 Preparing Build Summary 🚀' >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY

          echo "| Job Name        | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-----------------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| docker-build       | $DOCKER_STATUS |" >> $GITHUB_STEP_SUMMARY
          echo "| docker-scan       | $DOCKER_STATUS |" >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY

          echo '## Job ran by: ${{ github.actor }}' >> $GITHUB_STEP_SUMMARY